import type { RouteModule } from "../index";
import {
  authLimiter,
  commandLimiter,
  dataCollectionLimiter,
  dataProcessLimiter,
  deeplxLimiter,
  deeplxPublicLimiter,
  historyLimiter,
  ipfsLimiter,
  libreChatLimiter,
  lifeLimiter,
  mediaLimiter,
  meEndpointLimiter,
  networkLimiter,
  oauthLimiter,
  passkeyLimiter,
  socialLimiter,
  statusLimiter,
  tamperLimiter,
  totpLimiter,
  ttsLimiter,
} from "../../middleware/routeLimiters";

export const routeLimiterModules: RouteModule[] = [
  {
    name: "auth-limiter",
    path: "/api/auth",
    router: authLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "auth-me-limiter",
    path: "/api/auth/me",
    router: meEndpointLimiter,
    requiresAuth: true,
    rateLimited: true,
    isPublic: false,
    rateLimitPolicy: {
      mode: "mount",
      limiters: ["meEndpointLimiter"],
      note: "Dedicated limiter mount for the authenticated /auth/me endpoint",
    },
  },
  {
    name: "tts-generate-limiter",
    path: "/api/tts/generate",
    router: ttsLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "tts-history-limiter",
    path: "/api/tts/history",
    router: historyLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "tts-jobs-limiter",
    path: "/api/tts/jobs",
    router: historyLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "totp-limiter",
    path: "/api/totp",
    router: totpLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "passkey-limiter",
    path: "/api/passkey",
    router: passkeyLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "tamper-limiter",
    path: "/api/tamper",
    router: tamperLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "command-limiter",
    path: "/api/command",
    router: commandLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "libre-chat-limiter",
    path: "/api/libre-chat",
    router: libreChatLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "data-collection-limiter",
    path: "/api/data-collection",
    router: dataCollectionLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "ipfs-limiter",
    path: "/api/ipfs",
    router: ipfsLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "network-limiter",
    path: "/api/network",
    router: networkLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "data-process-limiter",
    path: "/api/data",
    router: dataProcessLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "deeplx-limiter",
    path: "/api/deeplx",
    router: deeplxLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "deeplx-public-limiter",
    path: "/api/public/deeplx",
    router: deeplxPublicLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "media-limiter",
    path: "/api/media",
    router: mediaLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "social-limiter",
    path: "/api/social",
    router: socialLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "life-limiter",
    path: "/api/life",
    router: lifeLimiter,
    requiresAuth: false,
    rateLimited: true,
    isPublic: true,
  },
  {
    name: "status-limiter",
    path: "/api/status",
    router: statusLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
  {
    name: "oauth-limiter",
    path: "/api/oauth",
    router: oauthLimiter,
    requiresAuth: "mixed",
    rateLimited: true,
    isPublic: "mixed",
  },
];
