name: Docker Build Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  docker-build-check:
    name: Docker Build Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 22

      - name: Set Node.js memory limits
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=5096" >> $GITHUB_ENV
          echo "NPM_CONFIG_CACHE=/tmp/.npm" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=commit-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Docker Image
        id: docker-build
        uses: docker/build-push-action@master
        env:
          BUILDKIT_MEM_LIMIT: 13g
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_OPTIONS=--max-old-space-size=13000
          no-cache: true

      - name: Verify Push Success
        run: |
          echo "✅ Docker 镜像构建并推送成功"
          echo "镜像仓库: ghcr.io/${{ github.repository }}"
          echo "推送的标签:"
          echo "${{ steps.meta.outputs.tags }}"